### PR TITLE
Fix segfault with roaring64 intersect_with_range and empty bitmap

### LINKED ISSUE #635: Roaring64 segfault empty bitmap intersect with range
```c
roaring64_bitmap_t* r = roaring64_bitmap_create();
roaring64_bitmap_intersect_with_range(r, 0, 50000); // Segfault here
```

### PR DESCRIPTION
**Pull request by Dr-Emann**
Fixes #635, and adds some tests

@SLieve, is this the right place to do this? The segfault under valgrind:

```
[ RUN      ] test_intersect_with_range
==648093== Invalid read of size 1
==648093==    at 0x12A894: art_node_iterator_lower_bound (art.c:1633)
==648093==    by 0x12AB9F: art_iterator_lower_bound (art.c:1696)
==648093==    by 0x120D2B: roaring64_iterator_move_equalorlarger (roaring64.c:2087)
==648093==    by 0x11E5DB: roaring64_bitmap_intersect_with_range (roaring64.c:1126)
==648093==    by 0x10F3F7: (anonymous namespace)::test_intersect_with_range(void**) (roaring64_unit.cpp:1058)
==648093==    by 0x15B74B: cmocka_run_one_test_or_fixture (cmocka.c:2801)
==648093==    by 0x15BA3F: cmocka_run_one_tests (cmocka.c:2909)
==648093==    by 0x15BF67: _cmocka_run_group_tests (cmocka.c:3040)
==648093==    by 0x112E17: main (roaring64_unit.cpp:1897)
==648093==  Address 0x1 is not stack'd, malloc'd or (recently) free'd
==648093==
[  ERROR   ] --- Test failed with exception: Segmentation fault(11)
[  FAILED  ] test_intersect_with_range
```

The actual error seems to comes from `art_node_iterator_lower_bound` when passed a NULL node, not sure if this is the right place to guard, or if something lower down in the call chain should handle an empty bitmap better.

### CODE REVIEW

**Comment by Dr-Emann** [comment]
Ah, this also picked up a random change I had to mark the now unused sum_value field as deprecated with CROARING_DEPRECATED

**Comment by Dr-Emann** [comment]
Looks like I can get something similar with `roaring64_iterator_move_equalorlarger` on an empty bitmap directly as well.

**Comment by SLieve** [comment]
I think the right place to fix this would be in `art_iterator_lower_bound`. My reasoning is that it would be useful for our internal code or the user to be able to (indirectly) call this on a possibly empty bitmap, without checking first.

File: src/art/art.c [hunk 1]
```diff
@@ -1693,8 +1693,11 @@ bool art_iterator_lower_bound(art_iterator_t *iterator,
         // a valid key. Start from the root.
         iterator->frame = 0;
         iterator->depth = 0;
-        return art_node_iterator_lower_bound(art_iterator_node(iterator),
-                                             iterator, key);
+        art_node_t *root = art_iterator_node(iterator);
+        if (root == NULL) {
+            return false;
+        }
+        return art_node_iterator_lower_bound(root, iterator, key);
```
Comment (SLieve) [inline src/art/art.c:1700]: Could you add a test in art_unit for this case?

**Review by SLieve — APPROVED** [review]

**Review by lemire — APPROVED** [review]
We should merge and release 'soon'.

**Comment by Dr-Emann** [comment]
Ready when you are 👍

**Comment by lemire** [comment]
@Dr-Emann I am re-running a failed test which I do not expect to be related to this PR.

**Comment by Dr-Emann** [comment]
Anything else to do here? Would like to get this in and have a release with this in it.

**Comment by lemire** [comment]
Release upcoming.
